// Auto-generated by yuzer-embed-sync.py
// 0 eventos, R$ 0.00

import type { BarHistoryData } from './use-bar-data'

export const BAR_EMBED: BarHistoryData = {
  "source": "backup",
  "totalEvents": 0,
  "totalRevenue": 0,
  "totalOrders": 0,
  "totalItens": 0,
  "ticketMedioBar": 0,
  "ticketMedioGeral": 0,
  "eventos": [
  ],
  "eventBarRevenue": {
    "sympla-3420938": {"revenue": 15072.0, "transactions": 276, "perCapita": 54.61},
    "sympla-3457402": {"revenue": 43138.0, "transactions": 750, "perCapita": 57.52},
    "sympla-3474070": {"revenue": 8562.0, "transactions": 172, "perCapita": 49.78},
    "sympla-3477015": null,
    "sympla-3492296": {"revenue": 22433.0, "transactions": 534, "perCapita": 42.01},
    "sympla-3500838": null
  },
  "mensais": [
  ],
  "produtoMix": [
  ],
  "metodosPagamento": [],
  "categorias": [
  ]
}
