// Auto-generated by gerar-embeds.py — DADOS REAIS DO BANCO DE PRODUCAO
// 40 eventos, R$ 726,321.88

import type { BarHistoryData } from './use-bar-data'

export interface EventBarRevenue {
  revenue: number
  transactions: number
  perCapita: number
}

export const BAR_EMBED: BarHistoryData = {
  "source": "database",
  "totalEvents": 46,
  "totalRevenue": 726321.88,
  "totalOrders": 18695,
  "totalItens": 0,
  "ticketMedioBar": 0,
  "ticketMedioGeral": 0,
  "eventos": [
    {
      "start": "2026-04-15",
      "end": "2026-04-16",
      "days": 1,
      "orders": 849,
      "revenue": 30293.15,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2026-03-11",
      "end": "2026-03-12",
      "days": 1,
      "orders": 759,
      "revenue": 25633.00,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2026-02-04",
      "end": "2026-02-05",
      "days": 1,
      "orders": 598,
      "revenue": 16951.00,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2026-01-14",
      "end": "2026-01-15",
      "days": 1,
      "orders": 544,
      "revenue": 18592.00,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2025-12-10",
      "end": "2025-12-11",
      "days": 1,
      "orders": 841,
      "revenue": 83578.00,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2025-11-12",
      "end": "2025-11-13",
      "days": 1,
      "orders": 533,
      "revenue": 17390.00,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2025-10-15",
      "end": "2025-10-16",
      "days": 1,
      "orders": 521,
      "revenue": 13415.00,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2025-10-06",
      "end": "2025-10-07",
      "days": 1,
      "orders": 0,
      "revenue": 0.00,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2025-09-10",
      "end": "2025-09-11",
      "days": 1,
      "orders": 854,
      "revenue": 65403.00,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2025-08-10",
      "end": "2025-08-11",
      "days": 1,
      "orders": 449,
      "revenue": 13111.00,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2025-08-07",
      "end": "2025-08-08",
      "days": 1,
      "orders": 478,
      "revenue": 17167.00,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2025-07-09",
      "end": "2025-07-10",
      "days": 1,
      "orders": 505,
      "revenue": 19007.00,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2025-06-11",
      "end": "2025-06-12",
      "days": 1,
      "orders": 571,
      "revenue": 28126.02,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2025-05-15",
      "end": "2025-05-16",
      "days": 1,
      "orders": 28,
      "revenue": 1155.00,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2025-05-07",
      "end": "2025-05-08",
      "days": 1,
      "orders": 430,
      "revenue": 12204.94,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2025-04-09",
      "end": "2025-04-10",
      "days": 1,
      "orders": 1033,
      "revenue": 52234.69,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2025-03-11",
      "end": "2025-03-12",
      "days": 1,
      "orders": 123,
      "revenue": 2700.00,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2025-02-12",
      "end": "2025-02-13",
      "days": 1,
      "orders": 449,
      "revenue": 13639.00,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2025-01-15",
      "end": "2025-01-16",
      "days": 1,
      "orders": 475,
      "revenue": 11984.00,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2025-01-06",
      "end": "2025-01-07",
      "days": 1,
      "orders": 0,
      "revenue": 0.00,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2024-12-05",
      "end": "2024-12-06",
      "days": 1,
      "orders": 641,
      "revenue": 24940.00,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2024-11-13",
      "end": "2024-11-14",
      "days": 1,
      "orders": 617,
      "revenue": 21061.00,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2024-11-11",
      "end": "2024-11-12",
      "days": 1,
      "orders": 0,
      "revenue": 0.00,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2024-10-16",
      "end": "2024-10-17",
      "days": 1,
      "orders": 465,
      "revenue": 11837.00,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2024-10-09",
      "end": "2024-10-10",
      "days": 1,
      "orders": 624,
      "revenue": 22924.00,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2024-09-11",
      "end": "2024-09-12",
      "days": 1,
      "orders": 603,
      "revenue": 20821.00,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2024-08-21",
      "end": "2024-08-22",
      "days": 1,
      "orders": 317,
      "revenue": 8350.00,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2024-08-14",
      "end": "2024-08-15",
      "days": 1,
      "orders": 1025,
      "revenue": 40007.68,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2024-07-10",
      "end": "2024-07-11",
      "days": 1,
      "orders": 528,
      "revenue": 14653.00,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2024-06-12",
      "end": "2024-06-13",
      "days": 1,
      "orders": 589,
      "revenue": 19031.00,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2024-05-08",
      "end": "2024-05-09",
      "days": 1,
      "orders": 384,
      "revenue": 9100.00,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2024-04-10",
      "end": "2024-04-11",
      "days": 1,
      "orders": 656,
      "revenue": 24491.28,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2024-03-21",
      "end": "2024-03-22",
      "days": 1,
      "orders": 275,
      "revenue": 5008.08,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2024-03-07",
      "end": "2024-03-08",
      "days": 1,
      "orders": 0,
      "revenue": 0.00,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2024-01-25",
      "end": "2024-01-26",
      "days": 1,
      "orders": 240,
      "revenue": 4906.00,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2024-01-17",
      "end": "2024-01-18",
      "days": 1,
      "orders": 582,
      "revenue": 16030.00,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2023-12-14",
      "end": "2023-12-15",
      "days": 1,
      "orders": 399,
      "revenue": 10697.04,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2023-11-09",
      "end": "2023-11-10",
      "days": 1,
      "orders": 710,
      "revenue": 29881.00,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2023-10-11",
      "end": "2023-10-12",
      "days": 1,
      "orders": 0,
      "revenue": 0.00,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2023-08-10",
      "end": "2023-08-11",
      "days": 1,
      "orders": 0,
      "revenue": 0.00,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2026-05-22",
      "end": "2026-05-23",
      "days": 1,
      "orders": 0,
      "revenue": 0,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2026-05-14",
      "end": "2026-05-15",
      "days": 1,
      "orders": 0,
      "revenue": 0,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2026-05-06",
      "end": "2026-05-07",
      "days": 1,
      "orders": 0,
      "revenue": 0,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2026-05-03",
      "end": "2026-05-04",
      "days": 1,
      "orders": 0,
      "revenue": 0,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2026-04-28",
      "end": "2026-04-29",
      "days": 1,
      "orders": 0,
      "revenue": 0,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
    {
      "start": "2026-04-18",
      "end": "2026-04-19",
      "days": 1,
      "orders": 0,
      "revenue": 0,
      "ticketMedio": 0,
      "itensVendidos": 0,
      "produtos": [],
      "metodosPagamento": []
    },
  ],
  "eventBarRevenue": {
<<<<<<< Updated upstream
    "sympla-3384296": {
      "revenue": 30293.15,
      "transactions": 849,
      "perCapita": 35.68
    },
    "sympla-3332505": {
      "revenue": 25633.00,
      "transactions": 759,
      "perCapita": 33.77
    },
    "sympla-3297245": {
      "revenue": 16951.00,
      "transactions": 598,
      "perCapita": 28.35
    },
    "sympla-3272845": {
      "revenue": 18592.00,
      "transactions": 544,
      "perCapita": 34.18
    },
    "sympla-3245686": {
      "revenue": 83578.00,
      "transactions": 841,
      "perCapita": 99.38
    },
    "sympla-3209412": {
      "revenue": 17390.00,
      "transactions": 533,
      "perCapita": 32.63
    },
    "sympla-3168880": {
      "revenue": 13415.00,
      "transactions": 521,
      "perCapita": 25.75
    },
    "sympla-3150968": null,
    "sympla-3113883": {
      "revenue": 65403.00,
      "transactions": 854,
      "perCapita": 76.58
    },
    "sympla-3073170": {
      "revenue": 13111.00,
      "transactions": 449,
      "perCapita": 29.2
    },
    "sympla-3060095": {
      "revenue": 17167.00,
      "transactions": 478,
      "perCapita": 35.91
    },
    "sympla-3028036": {
      "revenue": 19007.00,
      "transactions": 505,
      "perCapita": 37.64
    },
    "sympla-2987008": {
      "revenue": 28126.02,
      "transactions": 571,
      "perCapita": 49.26
    },
    "cmowubrg505sftua7duoe1ojk": {
      "revenue": 1155.00,
      "transactions": 28,
      "perCapita": 41.25
    },
    "sympla-2942257": {
      "revenue": 12204.94,
      "transactions": 430,
      "perCapita": 28.38
    },
    "sympla-2887562": {
      "revenue": 52234.69,
      "transactions": 1033,
      "perCapita": 50.57
    },
    "sympla-2862206": {
      "revenue": 2700.00,
      "transactions": 123,
      "perCapita": 21.95
    },
    "sympla-2828931": {
      "revenue": 13639.00,
      "transactions": 449,
      "perCapita": 30.38
    },
    "sympla-2795323": {
      "revenue": 11984.00,
      "transactions": 475,
      "perCapita": 25.23
    },
    "sympla-2785141": null,
    "sympla-2754645": {
      "revenue": 24940.00,
      "transactions": 641,
      "perCapita": 38.91
    },
    "sympla-2729608": {
      "revenue": 21061.00,
      "transactions": 617,
      "perCapita": 34.13
    },
    "sympla-2721616": null,
    "sympla-2686304": {
      "revenue": 11837.00,
      "transactions": 465,
      "perCapita": 25.46
    },
    "sympla-2675465": {
      "revenue": 22924.00,
      "transactions": 624,
      "perCapita": 36.74
    },
    "sympla-2633353": {
      "revenue": 20821.00,
      "transactions": 603,
      "perCapita": 34.53
    },
    "cmowubs7u0a0wtua7mzroohak": {
      "revenue": 8350.00,
      "transactions": 317,
      "perCapita": 26.34
    },
    "cmowubsat0a9qtua7cydohe8k": {
      "revenue": 40007.68,
      "transactions": 1025,
      "perCapita": 39.03
    },
    "cmowubsej0b28tua7nxx9qkg8": {
      "revenue": 14653.00,
      "transactions": 528,
      "perCapita": 27.75
    },
    "cmowubshe0bgxtua70qoojntf": {
      "revenue": 19031.00,
      "transactions": 589,
      "perCapita": 32.31
    },
    "cmowubsjx0bxbtua7thjxu0s1": {
      "revenue": 9100.00,
      "transactions": 384,
      "perCapita": 23.7
    },
    "cmowubsml0c80tua7xboaj3ew": {
      "revenue": 24491.28,
      "transactions": 656,
      "perCapita": 37.33
    },
    "cmos4gx76000ftuzo0zg533i4": {
      "revenue": 5008.08,
      "transactions": 275,
      "perCapita": 18.21
    },
    "cmos4gwit000ctuzobv5wgzyb": null,
    "cmos4gvwi000btuzoc8pt324j": {
      "revenue": 4906.00,
      "transactions": 240,
      "perCapita": 20.44
    },
    "cmowubsuk0d4ktua7kgqhk7ad": {
      "revenue": 16030.00,
      "transactions": 582,
      "perCapita": 27.54
    },
    "cmos4gv9d0008tuzod1v6vohy": {
      "revenue": 10697.04,
      "transactions": 399,
      "perCapita": 26.81
    },
    "cmos4gumu0005tuzowyzny7xa": {
      "revenue": 29881.00,
      "transactions": 710,
      "perCapita": 42.09
    },
    "cmos4gtzk0002tuzo6qahavd8": null,
    "cmos4gt0l0001tuzohf8se5zp": null,
    "sarau-secreto-maio-2026": null,
    "sarau-secreto-convida-magrao": null,
    "sala-secreta": null,
    "sarau-secreto-convida-ellen-oleria": null,
    "sarau-secreto-convida-sotam": null,
    "sarau-secreto-solsticio-de-inverno": null,
=======
    "2026-07-16": {"revenue": 29423.0, "transactions": 627, "perCapita": 46.93},
    "2026-07-09": {"revenue": 22433.0, "transactions": 534, "perCapita": 42.01},
    "2026-06-25": {"revenue": 8562.0, "transactions": 172, "perCapita": 49.78},
    "2026-06-10": {"revenue": 43138.0, "transactions": 750, "perCapita": 57.52},
    "2026-05-14": {"revenue": 15072.0, "transactions": 276, "perCapita": 54.61},
    "2026-04-16": {"revenue": 30293.0, "transactions": 595, "perCapita": 50.91},
    "2026-03-12": {"revenue": 25633.0, "transactions": 571, "perCapita": 44.89},
    "2026-02-05": {"revenue": 16951.0, "transactions": 369, "perCapita": 45.94},
    "2026-01-15": {"revenue": 18592.0, "transactions": 462, "perCapita": 40.24},
    "2025-12-11": {"revenue": 83578.0, "transactions": 1852, "perCapita": 45.13},
    "2025-11-13": {"revenue": 17390.0, "transactions": 419, "perCapita": 41.5},
    "2025-10-16": {"revenue": 13415.0, "transactions": 413, "perCapita": 32.48},
    "2025-09-11": {"revenue": 65403.0, "transactions": 1508, "perCapita": 43.37},
    "2025-08-14": {"revenue": 13111.0, "transactions": 284, "perCapita": 46.17},
    "2025-08-08": {"revenue": 17167.0, "transactions": 481, "perCapita": 35.69},
    "2025-07-10": {"revenue": 19007.0, "transactions": 359, "perCapita": 52.94},
    "2025-06-12": {"revenue": 28126.0, "transactions": 534, "perCapita": 52.67},
    "2025-05-16": {"revenue": 1155.0, "transactions": 20, "perCapita": 57.75},
    "2025-05-08": {"revenue": 12205.0, "transactions": 269, "perCapita": 45.37},
    "2025-04-10": {"revenue": 52235.0, "transactions": 1372, "perCapita": 38.07},
    "2025-03-12": {"revenue": 2700.0, "transactions": 73, "perCapita": 36.99},
    "2025-02-13": {"revenue": 13639.0, "transactions": 312, "perCapita": 43.71},
    "2025-01-16": {"revenue": 11984.0, "transactions": 388, "perCapita": 30.89},
    "2024-12-06": {"revenue": 24940.0, "transactions": 645, "perCapita": 38.67},
    "2024-11-14": {"revenue": 21061.0, "transactions": 546, "perCapita": 38.57},
    "2024-10-17": {"revenue": 11837.0, "transactions": 308, "perCapita": 38.43},
    "2024-10-10": {"revenue": 22924.0, "transactions": 621, "perCapita": 36.91},
    "2024-09-12": {"revenue": 7125.0, "transactions": 240, "perCapita": 29.69},
    "sympla-3420938": {"revenue": 15072.0, "transactions": 276, "perCapita": 54.61},
    "sympla-3457402": {"revenue": 43138.0, "transactions": 750, "perCapita": 57.52},
    "sympla-3474070": {"revenue": 8562.0, "transactions": 172, "perCapita": 49.78},
    "sympla-3477015": null,
    "sympla-3492296": {"revenue": 22433.0, "transactions": 534, "perCapita": 42.01},
    "sympla-3500838": {"revenue": 29423.0, "transactions": 627, "perCapita": 46.93}
>>>>>>> Stashed changes
  },
  "mensais": [],
  "produtoMix": [
    {
      "name": "VINHO",
      "qty": 998,
      "total": 184522.00,
      "pct": 25.4
    },
    {
      "name": "CERVEJA SPATEN LONG NECK ",
      "qty": 2218,
      "total": 118940.00,
      "pct": 16.4
    },
    {
      "name": "Vinho Chac Chac Malbec",
      "qty": 518,
      "total": 40438.00,
      "pct": 5.6
    },
    {
      "name": "AGUA SEM GAS",
      "qty": 2183,
      "total": 28498.00,
      "pct": 3.9
    },
    {
      "name": "CHAC CHAC MALBEC ROSE",
      "qty": 339,
      "total": 26485.00,
      "pct": 3.6
    },
    {
      "name": "TAÇA ",
      "qty": 1663,
      "total": 23004.94,
      "pct": 3.2
    },
    {
      "name": "Vinho Undurraga Carmenere",
      "qty": 280,
      "total": 22220.00,
      "pct": 3.1
    },
    {
      "name": "Vinho Undurraga Merlot",
      "qty": 248,
      "total": 19439.00,
      "pct": 2.7
    },
    {
      "name": "Vinho Undurraga Cabernet Sauvignon",
      "qty": 232,
      "total": 18224.00,
      "pct": 2.5
    },
    {
      "name": "Vinho Chac Chac Cabernet ",
      "qty": 216,
      "total": 16626.00,
      "pct": 2.3
    },
    {
      "name": "CERVEJA SPATEN",
      "qty": 450,
      "total": 15736.00,
      "pct": 2.2
    },
    {
      "name": "UVITA BLEND TINTO",
      "qty": 152,
      "total": 13753.00,
      "pct": 1.9
    },
    {
      "name": "AGUA COM GAS",
      "qty": 1460,
      "total": 12749.00,
      "pct": 1.8
    },
    {
      "name": "Spaten Long Neck",
      "qty": 200,
      "total": 12446.00,
      "pct": 1.7
    },
    {
      "name": "Chac Chac Cabernet Franc ",
      "qty": 147,
      "total": 11794.00,
      "pct": 1.6
    },
    {
      "name": "SANTA ANGÉLICA ROSE",
      "qty": 99,
      "total": 8919.00,
      "pct": 1.2
    },
    {
      "name": "Coca Cola",
      "qty": 955,
      "total": 7506.00,
      "pct": 1.0
    },
    {
      "name": "ÁGUA SEM GÁS",
      "qty": 586,
      "total": 6408.00,
      "pct": 0.9
    },
    {
      "name": "Coca Cola Zero",
      "qty": 801,
      "total": 6238.08,
      "pct": 0.9
    },
    {
      "name": "Vinho Finca Premiada Chile",
      "qty": 74,
      "total": 5772.00,
      "pct": 0.8
    },
    {
      "name": "Vinho Finca Premiada/Los Andes ",
      "qty": 73,
      "total": 5694.00,
      "pct": 0.8
    },
    {
      "name": "HEINEKEN LONG NECK",
      "qty": 282,
      "total": 5581.00,
      "pct": 0.8
    },
    {
      "name": "VIEIRA CAMPOS VINHO VERDE",
      "qty": 58,
      "total": 5514.00,
      "pct": 0.8
    },
    {
      "name": "Segundo Rosé ",
      "qty": 66,
      "total": 5412.00,
      "pct": 0.7
    },
    {
      "name": "BODEGA PRIVADA BRANCO",
      "qty": 60,
      "total": 5403.00,
      "pct": 0.7
    },
    {
      "name": "RED BULL TRADICIONAL",
      "qty": 272,
      "total": 5170.00,
      "pct": 0.7
    },
    {
      "name": "STELLA PURE GOLD ",
      "qty": 264,
      "total": 5102.00,
      "pct": 0.7
    },
    {
      "name": "CERVEJA LONG NECK ZERO",
      "qty": 277,
      "total": 4979.15,
      "pct": 0.7
    },
    {
      "name": "ÁGUA COM GÁS",
      "qty": 542,
      "total": 4648.00,
      "pct": 0.6
    },
    {
      "name": "RED BULL SUGAR FREE",
      "qty": 231,
      "total": 4482.00,
      "pct": 0.6
    },
  ],
  "metodosPagamento": [],
  "categorias": []
}
