// Auto-generated by preprocess-db.sh — DADOS REAIS DO BANCO DE PRODUCAO
// Regenere com: npm run preprocess-db
// NAO edite manualmente

	export interface EmbeddedEvent {
	  id: string; title: string; date: string; symplaEventId: string | null
	  soldCount: number | null; totalRevenue: number | null; capacity: number | null
	  status: string | null
	}

export interface EmbeddedTicketSummary {
  count: number; revenue: number
}

export interface EmbeddedDB {
  events: EmbeddedEvent[]
  tickets: Record<string, EmbeddedTicketSummary>
}

export const EMBEDDED_DB: EmbeddedDB = {
  "events": [
    {
      "id": "cmrnviefx0001tu4f996ot234",
      "title": "SARAU SECRETO CONVIDA LETÍCIA FIALHO",
      "date": "1691708400000",
      "symplaEventId": "2099414",
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "cmrnviepc0002tu4fi9cw4eok",
      "title": "Sarau Secreto",
      "date": "1697065200000",
      "symplaEventId": "2195243",
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "cmrnviez40005tu4fp7m8c25k",
      "title": "Sarau Secreto Convida Os Garotin",
      "date": "1699570800000",
      "symplaEventId": "2223526",
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "cmrnvif9v000atu4forpiez5j",
      "title": "Sarau Secreto",
      "date": "1702594800000",
      "symplaEventId": "2274987",
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "cmrnvifjr000dtu4f36wty4uh",
      "title": "AFTER SECRETO",
      "date": "1706223600000",
      "symplaEventId": "2310761",
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "cmrnvifst000etu4ftquvta1b",
      "title": "Sarau Secreto Convida Youn",
      "date": "1709852400000",
      "symplaEventId": "2357961",
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "cmrnvig2g000htu4f0ntp1itg",
      "title": "After Secreto - Antonela",
      "date": "1711062000000",
      "symplaEventId": "2373126",
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    }
  ],
  "tickets": {
    "cmrnviepc0002tu4fi9cw4eok": {
      "count": 1,
      "revenue": 33.0
    },
    "cmrnviez40005tu4fp7m8c25k": {
      "count": 2,
      "revenue": 198.0
    },
    "cmrnvif9v000atu4forpiez5j": {
      "count": 1,
      "revenue": 33.0
    },
    "cmrnvifst000etu4ftquvta1b": {
      "count": 1,
      "revenue": 88.0
    }
  }
}
