// Auto-generated by gerar-embeds.py — DADOS REAIS DO BANCO DE PRODUCAO
// Regenerado automaticamente via cron
// NAO edite manualmente — alteracoes serao sobrescritas

export interface EmbeddedEvent {
  id: string; title: string; date: string; symplaEventId: string | null
  soldCount: number | null; totalRevenue: number | null; capacity: number | null
  status: string | null
}

export interface EmbeddedTicketSummary {
  count: number; revenue: number
}

export interface EmbeddedDB {
  events: EmbeddedEvent[]
  tickets: Record<string, EmbeddedTicketSummary>
}

export const EMBEDDED_DB: EmbeddedDB = {
  "events": [
    {
      "id": "sympla-3384296",
      "title": "Sarau Secreto Convida Leticia Fialho",
      "date": "1776297600000",
      "symplaEventId": "3384296",
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "sympla-3332505",
      "title": "Sarau Secreto - No caminho da arte",
      "date": "1773273600000",
      "symplaEventId": "3332505",
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "sympla-3297245",
      "title": "Sarau Secreto",
      "date": "1770249600000",
      "symplaEventId": "3297245",
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "sympla-3272845",
      "title": "Sarau Secreto - Janeiro 2026",
      "date": "1768435200000",
      "symplaEventId": "3272845",
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "sympla-3245686",
      "title": "Sarau Secreto - Ultimo Ato",
      "date": "1765411200000",
      "symplaEventId": "3245686",
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "sympla-3209412",
      "title": "SARAU SECRETO",
      "date": "1762992000000",
      "symplaEventId": "3209412",
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "sympla-3168880",
      "title": "Sarau secreto",
      "date": "1760572800000",
      "symplaEventId": "3168880",
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "sympla-3150968",
      "title": "Sarau Secreto - Rio de Janeiro",
      "date": "1759795200000",
      "symplaEventId": "3150968",
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "sympla-3113883",
      "title": "Sarau Secreto 3 anos.",
      "date": "1757548800000",
      "symplaEventId": "3113883",
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "sympla-3073170",
      "title": "Sala Secreta",
      "date": "1754870400000",
      "symplaEventId": "3073170",
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "sympla-3060095",
      "title": "Sarau Secreto - Ceilandia",
      "date": "1754611200000",
      "symplaEventId": "3060095",
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "sympla-3028036",
      "title": "Sarau Secreto - Julho",
      "date": "1752105600000",
      "symplaEventId": "3028036",
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "sympla-2987008",
      "title": "SARAU SECRETO - JUNHO",
      "date": "1749686400000",
      "symplaEventId": "2987008",
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "cmowubrg505sftua7duoe1ojk",
      "title": "Sarau Secreto (2025-05-16)",
      "date": "1747353600000",
      "symplaEventId": null,
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "sympla-2942257",
      "title": "SARAU SECRETO",
      "date": "1746662400000",
      "symplaEventId": "2942257",
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "sympla-2887562",
      "title": "SARAU SECRETO CONVIDA JEAN TASSY",
      "date": "1744243200000",
      "symplaEventId": "2887562",
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "sympla-2862206",
      "title": "SALA SECRETA",
      "date": "1741737600000",
      "symplaEventId": "2862206",
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "sympla-2828931",
      "title": "SARAU SECRETO",
      "date": "1739404800000",
      "symplaEventId": "2828931",
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "sympla-2795323",
      "title": "Sarau Secreto",
      "date": "1736985600000",
      "symplaEventId": "2795323",
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "sympla-2785141",
      "title": "SARAU SECRETO - RIO DE JANEIRO",
      "date": "1736208000000",
      "symplaEventId": "2785141",
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "sympla-2754645",
      "title": "Sarau Secreto - O ultimo Ato",
      "date": "1733443200000",
      "symplaEventId": "2754645",
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "sympla-2729608",
      "title": "SARAU SECRETO CONVIDA IMBA",
      "date": "1731542400000",
      "symplaEventId": "2729608",
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "sympla-2721616",
      "title": "SARAU SECRETO - RIO DE JANEIRO",
      "date": "1731369600000",
      "symplaEventId": "2721616",
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "sympla-2686304",
      "title": "After Secreto - Black ipê Jazz",
      "date": "1729123200000",
      "symplaEventId": "2686304",
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "sympla-2675465",
      "title": "SARAU SECRETO",
      "date": "1728518400000",
      "symplaEventId": "2675465",
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "sympla-2633353",
      "title": "SARAU SECRETO - 2 ANOS",
      "date": "1726099200000",
      "symplaEventId": "2633353",
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "cmowubs7u0a0wtua7mzroohak",
      "title": "Sarau Secreto (2024-08-22)",
      "date": "1724284800000",
      "symplaEventId": null,
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "cmowubsat0a9qtua7cydohe8k",
      "title": "Sarau Secreto (2024-08-15)",
      "date": "1723680000000",
      "symplaEventId": null,
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "cmowubsej0b28tua7nxx9qkg8",
      "title": "Sarau Secreto (2024-07-11)",
      "date": "1720656000000",
      "symplaEventId": null,
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "cmowubshe0bgxtua70qoojntf",
      "title": "Sarau Secreto (2024-06-13)",
      "date": "1718236800000",
      "symplaEventId": null,
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "cmowubsjx0bxbtua7thjxu0s1",
      "title": "Sarau Secreto (2024-05-09)",
      "date": "1715212800000",
      "symplaEventId": null,
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "cmowubsml0c80tua7xboaj3ew",
      "title": "Sarau Secreto (2024-04-11)",
      "date": "1712793600000",
      "symplaEventId": null,
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "cmos4gx76000ftuzo0zg533i4",
      "title": "After Secreto - Antonela",
      "date": "1711062000000",
      "symplaEventId": null,
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "cmos4gwit000ctuzobv5wgzyb",
      "title": "Sarau Secreto Convida Youn",
      "date": "1709852400000",
      "symplaEventId": null,
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "cmos4gvwi000btuzoc8pt324j",
      "title": "AFTER SECRETO",
      "date": "1706223600000",
      "symplaEventId": null,
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "cmowubsuk0d4ktua7kgqhk7ad",
      "title": "Sarau Secreto (2024-01-18)",
      "date": "1705536000000",
      "symplaEventId": null,
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "cmos4gv9d0008tuzod1v6vohy",
      "title": "Sarau Secreto",
      "date": "1702594800000",
      "symplaEventId": null,
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "cmos4gumu0005tuzowyzny7xa",
      "title": "Sarau Secreto Convida Os Garotin",
      "date": "1699570800000",
      "symplaEventId": null,
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "cmos4gtzk0002tuzo6qahavd8",
      "title": "Sarau Secreto",
      "date": "1697065200000",
      "symplaEventId": null,
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "cmos4gt0l0001tuzohf8se5zp",
      "title": "SARAU SECRETO CONVIDA LETÍCIA FIALHO",
      "date": "1691708400000",
      "symplaEventId": null,
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "sarau-secreto-convida-sotam",
      "title": "Sarau Secreto x Crema convidam Sotam",
      "date": "1779494400000",
      "symplaEventId": "3500838",
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "sarau-secreto-convida-ellen-oleria",
      "title": "Sarau Secreto Convida Ellen Oleria",
      "date": "1778803200000",
      "symplaEventId": "3492296",
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "sala-secreta",
      "title": "Sala Secreta",
      "date": "1778112000000",
      "symplaEventId": "3474070",
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "sarau-secreto-solsticio-de-inverno",
      "title": "Sarau Secreto - Solstício de Inverno",
      "date": "1777852800000",
      "symplaEventId": "3477015",
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "sarau-secreto-convida-magrao",
      "title": "Sarau Secreto Convida Magrão",
      "date": "1777420800000",
      "symplaEventId": "3457402",
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
    {
      "id": "sarau-secreto-maio-2026",
      "title": "SARAU SECRETO - MAIO 2026",
      "date": "1776556800000",
      "symplaEventId": "3420938",
      "soldCount": null,
      "totalRevenue": null,
      "capacity": null,
      "status": "published"
    },
  ],
  "tickets": {}
}
