// preprocess-db.ts — Gera src/lib/db-embed.ts a partir do SQLite local
// Uso: npx tsx scripts/preprocess-db.ts
import { readFileSync, writeFileSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const DB_PATH = join(ROOT, 'packages/api/prisma/dev.db')

interface Event {
  id: string
  title: string
  date: string
  symplaEventId: string | null
  soldCount: number
  totalRevenue: number
  capacity: number | null
  status: string | null
  checkedIn: number
}

interface TicketSummary {
  count: number
  revenue: number
}

try {
  // Import better-sqlite3 (ou sql.js)
  const Database = (await import('better-sqlite3')).default
  const db = new Database(DB_PATH)

  const events = db.prepare(`
    SELECT id, title, date, symplaEventId, soldCount, totalRevenue, capacity, status
    FROM Event ORDER BY date ASC
  `).all() as any[]

  const tickets = db.prepare(`
    SELECT eventId, COUNT(*) as qty, COALESCE(SUM(totalPaid),0) as revenue_total
    FROM Ticket GROUP BY eventId
  `).all() as any[]

  db.close()

  const ticketsMap: Record<string, TicketSummary> = {}
  for (const t of tickets) {
    ticketsMap[t.eventId] = {
      count: Number(t.qty),
      revenue: Number(t.revenue_total),
    }
  }

  const output = `// Auto-generated by preprocess-db.ts — DADOS REAIS DO BANCO DE PRODUÇÃO
// Regenere com: npm run preprocess-db
// NÃO edite manualmente — este arquivo é substituído a cada build.

export interface EmbeddedEvent {
  id: string
  title: string
  date: string
  symplaEventId: string | null
  soldCount: number
  totalRevenue: number
  capacity: number | null
  status: string | null
}

export interface EmbeddedTicketSummary {
  count: number
  revenue: number
}

export interface EmbeddedDB {
  events: EmbeddedEvent[]
  tickets: Record<string, EmbeddedTicketSummary>
}

export const EMBEDDED_DB: EmbeddedDB = ${JSON.stringify({ events, tickets: ticketsMap }, null, 2)}
`

  writeFileSync(join(ROOT, 'src/lib/db-embed.ts'), output, 'utf-8')
  console.log('✅ db-embed.ts gerado com', events.length, 'eventos e', tickets.length, 'resumos de ticket')
} catch (e: any) {
  console.error('❌ Erro ao gerar db-embed.ts:', e.message)
  process.exit(1)
}
