#!/bin/bash
# preprocess-db.sh — Gera src/lib/db-embed.ts a partir do SQLite local
# Uso: bash scripts/preprocess-db.sh

set -e
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
DB="$ROOT/app/packages/api/prisma/dev.db"
OUT="$(cd "$(dirname "$0")/.." && pwd)/src/lib/db-embed.ts"

if [ ! -f "$DB" ]; then
  echo "❌ Banco não encontrado: $DB"
  exit 1
fi

python3 -c "
import sqlite3, json

db = sqlite3.connect('$DB')
db.row_factory = sqlite3.Row

events = [dict(r) for r in db.execute(
    'SELECT id, title, date, symplaEventId, soldCount, totalRevenue, capacity, status FROM Event ORDER BY date'
)]
for e in events:
    e['date'] = str(e['date'])
    for k in ['soldCount', 'totalRevenue', 'capacity']:
        if e[k] is not None:
            try: e[k] = int(float(str(e[k]))) if k in ('soldCount','capacity') else float(str(e[k]))
            except: pass
    e['symplaEventId'] = str(e['symplaEventId']) if e['symplaEventId'] else None

tickets_map = {}
for r in db.execute('SELECT eventId, COUNT(*) as qty, COALESCE(SUM(totalPaid),0) as revenue_total FROM Ticket GROUP BY eventId'):
    tickets_map[r[0]] = {'count': int(r[1]), 'revenue': float(str(r[2]))}

data = {'events': events, 'tickets': tickets_map}

ts = f'''// Auto-generated by preprocess-db.sh — DADOS REAIS DO BANCO DE PRODUCAO
// Regenere com: npm run preprocess-db
// NAO edite manualmente

\texport interface EmbeddedEvent {{
	  id: string; title: string; date: string; symplaEventId: string | null
	  soldCount: number | null; totalRevenue: number | null; capacity: number | null
	  status: string | null
	}}

export interface EmbeddedTicketSummary {{
  count: number; revenue: number
}}

export interface EmbeddedDB {{
  events: EmbeddedEvent[]
  tickets: Record<string, EmbeddedTicketSummary>
}}

export const EMBEDDED_DB: EmbeddedDB = {json.dumps(data, indent=2, ensure_ascii=False, default=str)}
'''

with open('$OUT', 'w') as f:
    f.write(ts)

count = len(events)
ticket_count = sum(t['count'] for t in tickets_map.values())
print(f'✅ db-embed.ts gerado com {count} eventos e {ticket_count} tickets')
" 2>&1

echo "Done"
